#!/usr/bin/env bash
#
# Watch a folder, commit and push when changes are detected
#   usage: ./auto_commit.sh folder_name

folder_checksum() {
  echo "$(tar -cf - "$1" | md5)"
}

timestamp() {
  echo "$(date "+%Y%m%d %H%M%S")"
}

auto_commit_and_push() {
  git add .
  git commit -m "auto-commit $pathname at $1"
  git push origin HEAD
}

first_run=true
pathname=$1
initial_checksum=$(folder_checksum "$pathname")
script=$(basename "$0")
wait_time=30 # seconds

while true; do
  current_checksum=$(folder_checksum "$pathname")

  if [[ "$initial_checksum" != "$current_checksum" ]]; then
    current_timestamp=$(timestamp)
    echo
    echo "$script: publishing changes at $current_timestamp"
    auto_commit_and_push "$current_timestamp"
    initial_checksum=$current_checksum
  fi

  if [[ "$first_run" == "true" && "$initial_checksum" == "$current_checksum" ]]; then
    echo "$script: no changes, yet..."
    first_run=false
  fi

  sleep "$wait_time"
done
